# Use an official Python image
FROM python:3.13

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# Run your app (adjust this as needed)
CMD ["python", "app.py"]